apiVersion: 1

datasources:
  - name: Circadian-Postgres
    uid: circadian-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: circadian
    isDefault: true
    jsonData:
      database: circadian
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: circadian
    editable: true
